blank_issues_enabled: false
contact_links:
  - name: 💬 Preguntas generales
    url: https://github.com/fdomcas/RenovRent-TFG-DAW-2/discussions
    about: Para dudas que no sean bugs ni features, usa Discussions