# Generated by Django 6.0.3 on 2026-04-07 18:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmuebles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.TextField()),
                ('fotos', models.FileField(upload_to='fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_caducidad', models.DateField()),
                ('Nombre_titular', models.CharField(max_length=100)),
                ('Estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=250)),
                ('Nikname', models.CharField(max_length=250, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('dni', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.inmuebles')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristicas_Inmuebles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_habitaciones', models.IntegerField()),
                ('num_wc', models.IntegerField()),
                ('m2', models.IntegerField()),
                ('espacios', models.TextField()),
                ('extras', models.TextField()),
                ('id_inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.inmuebles')),
            ],
        ),
        migrations.CreateModel(
            name='Dinero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dinero', models.IntegerField()),
                ('id_tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.tarjeta')),
            ],
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='id_usuario',
            field=models.ManyToManyField(to='Base.usuario'),
        ),
        migrations.CreateModel(
            name='Propuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('url', models.URLField()),
                ('estado', models.CharField(choices=[('Denegada', 'Denegada'), ('Revision', 'Revision'), ('Aceptada', 'Aceptada')], default='Revision', max_length=100)),
                ('ubicacion', models.TextField()),
                ('fotos', models.FileField(upload_to='fotos/')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('id_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.chat')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Inversiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('retorno_mensual', models.IntegerField()),
                ('retorno_anual', models.IntegerField()),
                ('id_inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.inmuebles')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.usuario')),
            ],
        ),
    ]
