# Generated by Django 6.0.4 on 2026-05-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_perfil_otp_activo_perfil_otp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
