// src/theme.js — Sistema de diseño RenovRent
export const T = {
  bg:           '#faf9f6',
  bgSecundario: '#f3f1ed',
  blanco:       '#ffffff',
  borde:        '#e8e4dc',
  bordeHover:   '#d4cfc5',
  texto:        '#111111',
  textoSuave:   '#4a4540',
  textoMuted:   '#9a9390',
  naranja:      '#E8621A',
  naranjaHover: '#d05515',
  naranjaLight: '#fdf0e8',
  verde:        '#166534',
  verdeBg:      '#dcfce7',
  rojo:         '#991b1b',
  rojoBg:       '#fee2e2',
  amarillo:     '#92400e',
  amarilloBg:   '#fef3c7',
  sombra:       '0 1px 3px rgba(0,0,0,0.06), 0 4px 16px rgba(0,0,0,0.06)',
  sombraHover:  '0 4px 8px rgba(0,0,0,0.08), 0 12px 32px rgba(0,0,0,0.10)',
  sombraModal:  '0 20px 60px rgba(0,0,0,0.18)',
  radio:        '12px',
  radioSm:      '8px',
  radioLg:      '16px',
  radioPill:    '999px',
  fontDisplay:  "'Playfair Display', Georgia, serif",
  fontBody:     "'Inter', 'Segoe UI', sans-serif",
}

export const G = {
  page:      { minHeight: '100vh', background: T.bg, fontFamily: T.fontBody },
  container: { maxWidth: '1100px', margin: '0 auto', padding: '2rem 1.5rem' },
  btnPrimario: {
    background: T.naranja, color: '#fff', border: 'none',
    borderRadius: T.radioSm, padding: '0.7rem 1.4rem',
    fontWeight: '600', fontSize: '0.9rem', cursor: 'pointer',
    fontFamily: T.fontBody, letterSpacing: '0.01em',
    transition: 'background 0.2s',
  },
  btnSecundario: {
    background: T.blanco, color: T.textoSuave, border: `1.5px solid ${T.borde}`,
    borderRadius: T.radioSm, padding: '0.7rem 1.4rem',
    fontWeight: '600', fontSize: '0.9rem', cursor: 'pointer',
    fontFamily: T.fontBody,
  },
  btnGhost: {
    background: 'none', color: T.textoSuave, border: 'none',
    borderRadius: T.radioSm, padding: '0.7rem 1.4rem',
    fontWeight: '600', fontSize: '0.9rem', cursor: 'pointer',
    fontFamily: T.fontBody,
  },
  btnPeligro: {
    background: T.rojoBg, color: T.rojo, border: 'none',
    borderRadius: T.radioSm, padding: '0.5rem 1rem',
    fontWeight: '600', fontSize: '0.82rem', cursor: 'pointer',
  },
  input: {
    padding: '0.7rem 1rem', borderRadius: T.radioSm,
    border: `1.5px solid ${T.borde}`, fontSize: '0.9rem',
    outline: 'none', width: '100%', fontFamily: T.fontBody,
    background: T.blanco, color: T.texto,
    transition: 'border-color 0.2s, box-shadow 0.2s', boxSizing: 'border-box',
  },
  label: {
    fontSize: '0.72rem', fontWeight: '700', color: T.textoMuted,
    textTransform: 'uppercase', letterSpacing: '0.07em',
    display: 'block', marginBottom: '0.35rem',
  },
  cardPadding: {
    background: T.blanco, borderRadius: T.radioLg,
    boxShadow: T.sombra, border: `1px solid ${T.borde}`, padding: '1.5rem',
  },
  toastOk: {
    position: 'fixed', top: '1.5rem', right: '1.5rem',
    padding: '0.9rem 1.4rem', borderRadius: T.radio,
    background: T.verdeBg, color: T.verde,
    fontWeight: '600', fontSize: '0.88rem', zIndex: 999,
    boxShadow: T.sombra, border: '1px solid #bbf7d0',
  },
  toastErr: {
    position: 'fixed', top: '1.5rem', right: '1.5rem',
    padding: '0.9rem 1.4rem', borderRadius: T.radio,
    background: T.rojoBg, color: T.rojo,
    fontWeight: '600', fontSize: '0.88rem', zIndex: 999,
    boxShadow: T.sombra, border: '1px solid #fecaca',
  },
  seccionLabel: {
    fontSize: '0.72rem', fontWeight: '700', color: T.naranja,
    textTransform: 'uppercase', letterSpacing: '0.1em',
    display: 'block', marginBottom: '2px',
  },
  h1: { fontFamily: T.fontDisplay, fontSize: '1.9rem', fontWeight: '700', color: T.texto, lineHeight: 1.2, margin: 0 },
  h2: { fontFamily: T.fontDisplay, fontSize: '1.3rem', fontWeight: '700', color: T.texto, margin: 0 },
  h3: { fontFamily: T.fontBody, fontSize: '1rem', fontWeight: '700', color: T.texto, margin: 0 },
  hr: { height: '1px', background: T.borde, border: 'none', margin: '1rem 0' },
  overlay: {
    position: 'fixed', inset: 0, background: 'rgba(10,8,6,0.55)',
    zIndex: 100, display: 'flex', alignItems: 'center',
    justifyContent: 'center', padding: '1rem', backdropFilter: 'blur(2px)',
  },
  modal: {
    background: T.blanco, borderRadius: T.radioLg,
    padding: '2rem', width: '100%', maxWidth: '560px',
    maxHeight: '90vh', overflowY: 'auto',
    boxShadow: T.sombraModal, border: `1px solid ${T.borde}`,
  },
}